# The formula of the Homebrew tap AuroraTape/homebrew-tap (#131).
#
# Generated by homebrew.yml from .github/homebrew/aurora-ltfs.rb.in in
# AuroraTape/aurora-ltfs: edit the template there, not the copy in the tap.

# macFUSE is a cask, which a formula cannot depend on: require it instead
class MacfuseRequirement < Requirement
  fatal true

  satisfy(build_env: false) { File.exist?("/usr/local/lib/pkgconfig/fuse.pc") }

  def message
    <<~EOS
      Aurora LTFS needs macFUSE:
        brew install --cask macfuse
    EOS
  end
end

class AuroraLtfs < Formula
  desc "Linear Tape File System (LTFS) implementation, mounts LTFS tapes with FUSE"
  homepage "https://github.com/AuroraTape/aurora-ltfs"
  url "https://github.com/AuroraTape/aurora-ltfs/releases/download/v1.0.1/aurora-ltfs-1.0.1.tar.gz"
  sha256 "42df00ffcd574088cd7a324ac29706d772855629252275868e72dd609d10fc77"
  license "BSD-3-Clause"

  bottle do
    root_url "https://github.com/AuroraTape/aurora-ltfs/releases/download/v1.0.1"
    sha256 cellar: "/opt/homebrew/Cellar", arm64_sequoia: "424ced36b4e12f7aa7e96975387979e21d1fb503815a868993054b20b047fa86"
  end

  depends_on "pkgconf" => :build
  depends_on "icu4c@78"
  depends_on "libxml2"
  depends_on MacfuseRequirement
  depends_on :macos
  depends_on "ossp-uuid"

  def install
    # macFUSE lives in /usr/local, which the compiler shims drop from the flags
    # when Homebrew is elsewhere (/opt/homebrew on Apple silicon), also through
    # a symlink: build against a copy of its headers, library and pkg-config
    # file in the build tree. The library keeps its install name,
    # /usr/local/lib/libfuse.2.dylib, which the binaries load.
    fuse = buildpath/"macfuse"
    (fuse/"include").mkpath
    cp_r "/usr/local/include/fuse", fuse/"include"
    (fuse/"lib").mkpath
    cp "/usr/local/lib/libfuse.2.dylib", fuse/"lib/libfuse.dylib"
    pc = File.read("/usr/local/lib/pkgconfig/fuse.pc").sub(/^prefix=.*$/, "prefix=#{fuse}")
    (fuse/"pkgconfig/fuse.pc").write pc
    ENV.prepend_path "PKG_CONFIG_PATH", fuse/"pkgconfig"
    # genrb and pkgdata, found through PATH
    ENV.prepend_path "PATH", formula_opt_bin("icu4c@78")

    system "./configure", *std_configure_args, "--sysconfdir=#{etc}",
           "LDFLAGS=-framework CoreFoundation -framework IOKit"
    system "make"
    system "make", "install"

    # The plugins through opt, not this version's Cellar: altfs.conf is kept
    # across upgrades when the user edited it
    inreplace etc/"altfs.conf", lib.to_s, opt_lib.to_s
  end

  def caveats
    <<~EOS
      macOS is a Tier 2 platform of Aurora LTFS: CI builds it and runs the
      tests that need no mount, the tape backend (iokit) is not tested with a
      drive by the project. Mounting needs macFUSE, with its kernel extension
      allowed, or with its FSKit backend (README, "macOS: mounting without
      the kernel extension").

      The configuration is #{etc}/altfs.conf.
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/altfs -V 2>&1")
    (testpath/"tape").mkpath
    system bin/"mkaltfs", "-e", "file", "-d", testpath/"tape", "-s", "TEST00", "-f", "-q"
    # The first check of a new volume updates the MAM coherency data: it exits
    # with 1, "corrected", and finds the volume consistent
    assert_match "ACK0019I", shell_output("#{bin}/altfsck -e file #{testpath}/tape 2>&1", 1)
  end
end
